language: go

branches:
   only:
      - master
      - /^v.*$/

# Necesitamos mask para hacer la integracion
# Instalamos desde github y lo copiamos a /usr/local/bin

before_install:
   - echo "Quien soy: $(whoami)Â·
   - cd /tmp
   - wget https://github.com/jakedeichert/mask/releases/download/v0.10.0/mask-v0.10.0-x86_64-unknown-linux-gnu.zip 
   - unzip -j mask-v0.10.0-x86_64-unknown-linux-gnu.zip 
(cd /tmp ; unzip mask.zip )
   - sudo cp /tmp/mask /usr/local/bin

# Script para lanzar el build
script: /bin/true


